services:
  web:
    build: .
    command: bash -c "rm -rf tmp/cache/* && rm -f tmp/pids/server.pid && bin/dev"
    tty: true
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=${RAILS_ENV}
    ports:
      - "127.0.0.1:3000:3000"
      - "192.168.68.74:3000:3000"
volumes:
  bundle_cache: